'use strict';
const RI=window.ReadingImport;
const readingButtons=[...document.querySelectorAll('[data-reading-filter]')];
const readingSearch=document.querySelector('#reading-search');
const readingList=document.querySelector('#reading-list');
const baseReadings=JSON.parse(document.querySelector('#reading-data').textContent).map(RI.cleanRecord);
const storageKey='xie-lab-reading-imports-v1';
let imports=[],readingTopic='all',pending=[],batchController=null,storageBlocked=false;
const status=document.querySelector('#import-status');
const storageStatus=document.querySelector('#storage-status');
function say(message){status.textContent=message;}
function persist(next){if(storageBlocked){storageStatus.textContent='Reload this page before saving changes; the saved library needs to be reloaded.';return false;}try{localStorage.setItem(storageKey,JSON.stringify(next));imports=next;storageStatus.textContent='Imported readings are saved in this browser. Export an updated page to include them in the website.';return true;}catch{storageStatus.textContent='Browser storage is unavailable or full. Nothing new was saved. Export your library or enable storage, then try again.';return false;}}
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'[]');if(!Array.isArray(saved))throw Error();for(const raw of saved){const e=RI.cleanRecord(raw);if(!RI.isDuplicate(e,[...baseReadings,...imports]))imports.push(e);}}catch{storageBlocked=true;storageStatus.textContent='Saved readings could not be loaded. Your saved data has not been overwritten; export a backup before making changes.';document.querySelector('#save-imports').disabled=true;}
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;};
function externalLink(text,url){const a=el('a','',text);a.href=RI.safeURL(url);a.target='_blank';a.rel='noopener';return a;}
function readingArticle(e,local=false){const node=el('article','reading-entry'+(e.foundational?' is-foundational':''));node.dataset.foundational=String(Boolean(e.foundational));node.dataset.readingCategories=e.categories.map(c=>RI.slugs[RI.topics.indexOf(c)]).join(' ');if(local)node.dataset.localReading='true';
 const top=el('div','reading-entry-top');top.append(el('span','',e.kind));if(e.foundational)top.append(el('span','foundation-badge','Foundational reading'));if(e.required||e.recommended)top.append(el('span','required-label',e.required?'Required':'Highly recommended'));node.append(top);
 const title=el('h2');title.append(e.url?externalLink(e.title,e.url):document.createTextNode(e.title));node.append(title);
 if(e.foundationFocus)node.append(el('p','foundation-focus',e.foundationFocus));
 if(e.meta)node.append(el('p','reading-meta',e.meta));if(e.note)node.append(el('p','reading-note',e.note));
 if(e.doi){const p=el('p','reading-doi');p.append(externalLink((e.doiLabel||'DOI')+': '+e.doi,RI.doiURL(e.doi)));node.append(p);}else if(e.doiNote||['Paper','Preprint'].includes(e.kind))node.append(el('p','reading-doi-note',e.doiNote||'DOI not provided.'));
 node.append(el('p','reading-tags',e.categories.join(' / ')));
 if(local){const actions=el('div','reading-local-actions');const label=el('label','','Topic ');const select=topicSelect(e.categories[0]);select.setAttribute('aria-label','Topic for '+e.title);label.append(select);actions.append(label);select.addEventListener('change',()=>{const next=imports.map(x=>x===e?{...e,categories:[select.value]}:x);if(persist(next)){renderImports();updateReadings();}else select.value=e.categories[0];});
 const remove=el('button','','Remove imported reading');remove.type='button';remove.addEventListener('click',()=>{if(persist(imports.filter(x=>x!==e))){renderImports();updateReadings();say('Removed “'+e.title+'” from your browser library.');}});actions.append(remove);node.append(actions);}return node;
}
function renderImports(){readingList.querySelectorAll('[data-local-reading]').forEach(e=>e.remove());for(const e of imports)readingList.append(readingArticle(e,true));const all=[...baseReadings,...imports];for(const button of readingButtons){const slug=button.dataset.readingFilter;button.querySelector('span').textContent=slug==='all'?all.length:slug==='foundations'?all.filter(e=>e.foundational).length:all.filter(e=>e.categories.includes(RI.topics[RI.slugs.indexOf(slug)])).length;}}
function updateReadings(){const query=readingSearch.value.trim().toLowerCase();let count=0;readingList.querySelectorAll('.reading-entry').forEach(entry=>{const searchable=[...entry.children].filter(x=>!x.classList.contains('reading-local-actions')).map(x=>x.textContent).join(' ').toLowerCase();const matches=(readingTopic==='all'||(readingTopic==='foundations'&&entry.dataset.foundational==='true')||entry.dataset.readingCategories.split(' ').includes(readingTopic))&&searchable.includes(query);entry.hidden=!matches;if(matches)count++;});readingButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.readingFilter===readingTopic)));document.querySelector('#reading-count').textContent=`${count} ${count===1?'reading':'readings'}`;document.querySelector('#reading-empty').hidden=count!==0;document.querySelector('.reading-topic-note').hidden=readingTopic!=='working-memory'||query!=='';}
function topicFromHash(){const value=location.hash.slice(1);readingTopic=(value==='foundations'||RI.slugs.includes(value))?value:'all';updateReadings();}
readingButtons.forEach(button=>button.addEventListener('click',()=>{readingTopic=button.dataset.readingFilter;history.replaceState(null,'',readingTopic==='all'?location.pathname:'#'+readingTopic);updateReadings();}));readingSearch.addEventListener('input',updateReadings);window.addEventListener('hashchange',topicFromHash);
function topicSelect(value){const select=el('select');RI.topics.forEach(topic=>{const option=el('option','',topic);option.value=topic;select.append(option);});select.value=value||'Paper Pool';return select;}
async function requestJSON(url,signal){const controller=new AbortController();const abort=()=>controller.abort();if(signal?.aborted)throw new DOMException('Cancelled','AbortError');signal?.addEventListener('abort',abort,{once:true});const timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{signal:controller.signal,headers:{Accept:'application/json'}});if(!response.ok)throw Error(response.status===429?'Metadata service is busy. Please retry shortly.':'Metadata lookup returned '+response.status+'.');return await response.json();}finally{clearTimeout(timeout);signal?.removeEventListener('abort',abort);}}
async function lookupDOI(doi,signal){let lastError;const sources=doi.toLowerCase().startsWith('10.48550/')?['datacite','crossref']:['crossref','datacite'];for(const source of sources){try{const data=await requestJSON((source==='crossref'?'https://api.crossref.org/works/':'https://api.datacite.org/dois/')+encodeURIComponent(doi),signal);const entry=source==='crossref'?RI.crossref(data.message):RI.datacite(data.data.attributes);if(!entry.title||RI.doi(entry.doi).toLowerCase()!==RI.doi(doi).toLowerCase())throw Error('Metadata does not match this DOI.');return entry;}catch(error){if(signal.aborted)throw error;lastError=error;}}throw lastError;}
async function lookupMissingDOI(entry,signal){const params=new URLSearchParams({'query.bibliographic':entry.title+' '+entry.meta,rows:'3'});const data=await requestJSON('https://api.crossref.org/works?'+params,signal);const matches=(data.message?.items||[]).map(RI.crossref).filter(e=>RI.titleKey(e.title)===RI.titleKey(entry.title)&&e.kind===entry.kind&&(!entry.firstAuthor||entry.firstAuthor===e.firstAuthor)&&(!entry.year||entry.year===e.year));return matches.length===1?matches[0]:null;}
function showPending(){const list=document.querySelector('#import-preview-list');list.replaceChildren();pending.forEach((item,index)=>{const row=el('article','import-preview-row');const checkLabel=el('label','import-check');const checkbox=el('input');checkbox.type='checkbox';checkbox.checked=true;checkbox.addEventListener('change',()=>item.selected=checkbox.checked);checkLabel.append(checkbox,el('span','',item.entry.title));row.append(checkLabel);if(item.entry.meta)row.append(el('p','reading-meta',item.entry.meta));if(item.entry.doi)row.append(el('p','reading-doi','DOI: '+item.entry.doi));if(item.warning)row.append(el('p','import-warning',item.warning));const label=el('label','import-topic','Suggested topic');const select=topicSelect(item.entry.categories[0]);select.id='import-topic-'+index;label.htmlFor=select.id;select.addEventListener('change',()=>{item.entry.categories=[select.value];});row.append(label,select,el('p','import-reason',item.reason));list.append(row);});document.querySelector('#import-review').hidden=!pending.length;}
function setBusy(busy){document.querySelector('#prepare-import').disabled=busy;document.querySelector('#import-input').disabled=busy;document.querySelector('#import-file').disabled=busy;document.querySelector('#cancel-import').hidden=!busy;document.querySelector('#import-tools').setAttribute('aria-busy',String(busy));}
document.querySelector('#prepare-import').addEventListener('click',async()=>{const parsed=RI.parseInput(document.querySelector('#import-input').value);pending=[];showPending();const errors=[...parsed.errors];if(!parsed.records.length){say(errors.join(' ')||'No readable records found. Use DOI, BibTeX, or RIS.');return;}if(parsed.records.length>100){say('Please import up to 100 readings at a time. No records were imported.');return;}batchController=new AbortController();const signal=batchController.signal;setBusy(true);let duplicates=0;
 try{for(let i=0;i<parsed.records.length;i++){if(signal.aborted)break;let entry=parsed.records[i];if(RI.isDuplicate(entry,[...baseReadings,...imports,...pending.map(p=>p.entry)])){duplicates++;continue;}say(`Looking up ${i+1} of ${parsed.records.length}…`);let warning='';try{if(entry.doi){const fresh=await lookupDOI(entry.doi,signal);entry={...entry,...fresh,abstract:fresh.abstract||entry.abstract,keywords:fresh.keywords||entry.keywords,categories:entry.categories||[],foundational:entry.foundational||false,foundationOrder:entry.foundationOrder,foundationFocus:entry.foundationFocus,note:entry.note||'',required:entry.required||false,recommended:entry.recommended||false};}else if(entry.title){const fresh=await lookupMissingDOI(entry,signal);if(fresh)entry={...entry,...fresh,abstract:fresh.abstract||entry.abstract,keywords:fresh.keywords||entry.keywords,categories:entry.categories||[],foundational:entry.foundational||false,foundationOrder:entry.foundationOrder,foundationFocus:entry.foundationFocus,note:entry.note||''};else warning='No unambiguous DOI match found. Original citation retained.';}}catch(error){if(signal.aborted)break;if(!entry.title){errors.push(entry.doi+': lookup failed; please retry or import a BibTeX/RIS citation.');continue;}warning='Metadata lookup unavailable. Using the citation you supplied; DOI not verified.';}
  if(RI.isDuplicate(entry,[...baseReadings,...imports,...pending.map(p=>p.entry)])){duplicates++;continue;}const suggestion=RI.classify(entry);entry.categories=entry.categories?.length?entry.categories:[suggestion.topic];const cleaned=RI.cleanRecord(entry);pending.push({entry:cleaned,reason:suggestion.reason+(suggestion.review?' Please check the suggested topic.':''),warning,selected:true});}
 }finally{setBusy(false);showPending();say((signal.aborted?'Lookup cancelled. ':'')+pending.length+' ready to import. '+duplicates+' duplicate(s) skipped.'+(errors.length?' '+errors.join(' '):''));batchController=null;}
});
document.querySelector('#cancel-import').addEventListener('click',()=>batchController?.abort());
document.querySelector('#import-file').addEventListener('change',async(event)=>{const files=[...event.target.files];if(!files.length)return;if(files.reduce((n,f)=>n+f.size,0)>1000000){say('Please choose files totaling less than 1 MB.');event.target.value='';return;}try{document.querySelector('#import-input').value=(await Promise.all(files.map(f=>f.text()))).join('\n');say('File loaded. Select “Find articles & suggest topics” to review it.');}catch{say('Unable to read this file. Try pasting its citation text instead.');}});
document.querySelector('#save-imports').addEventListener('click',()=>{const additions=[];for(const item of pending)if(item.selected&&!RI.isDuplicate(item.entry,[...baseReadings,...imports,...additions]))additions.push(item.entry);if(!additions.length){say('Select at least one new article.');return;}if(!persist([...imports,...additions]))return;pending=[];showPending();renderImports();readingTopic='all';readingSearch.value='';history.replaceState(null,'',location.pathname);updateReadings();say(additions.length+' reading(s) imported and assigned to their topics. Saved in this browser.');document.querySelector('#import-input').value='';document.querySelector('#import-file').value='';});
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.querySelector('#export-library').addEventListener('click',()=>{download('xie-lab-readings.json',JSON.stringify({version:1,entries:[...baseReadings,...imports]},null,2),'application/json');say('Library backup prepared. Import the downloaded JSON file to restore it in another browser.');});
document.querySelector('#export-page').addEventListener('click',()=>{const all=[...baseReadings,...imports];const copy=document.documentElement.cloneNode(true);const list=copy.querySelector('#reading-list');list.replaceChildren(...all.map(e=>readingArticle(e)));copy.querySelector('#reading-data').textContent=JSON.stringify(all).replace(/</g,'\\u003c');copy.querySelector('#reading-search').setAttribute('value','');copy.querySelector('#reading-count').textContent=all.length+' readings';copy.querySelector('#reading-empty').hidden=true;copy.querySelector('.reading-topic-note').hidden=true;copy.querySelector('#import-preview-list').replaceChildren();copy.querySelector('#import-review').hidden=true;copy.querySelector('#import-status').textContent='';copy.querySelector('#import-input').textContent='';copy.querySelector('#import-input').removeAttribute('disabled');copy.querySelector('#import-file').removeAttribute('disabled');copy.querySelector('#prepare-import').removeAttribute('disabled');copy.querySelector('#cancel-import').hidden=true;copy.querySelector('#import-tools').removeAttribute('open');copy.querySelector('#import-tools').setAttribute('aria-busy','false');copy.querySelector('#storage-status').textContent='Imported readings are saved in this browser. Export an updated page to include them in the website.';copy.querySelectorAll('[data-reading-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.readingFilter==='all')));copy.querySelector('.menu-toggle').setAttribute('aria-expanded','false');copy.querySelector('#navigation').classList.remove('is-open');download('suggested-readings.html','<!doctype html>\n'+copy.outerHTML,'text/html');say('Updated page prepared for download. Replace suggested-readings.html in your website folder to share these readings. Keep the other website files alongside it.');});
window.addEventListener('storage',event=>{if(event.key===storageKey){storageBlocked=true;storageStatus.textContent='The library changed in another tab. Reload this page before importing more readings.';document.querySelector('#save-imports').disabled=true;}});
renderImports();topicFromHash();
